version: '3.8'

services:
  frontend:
    volumes:
      - ./Client:/app
      - /app/node_modules
    command: npm run dev

  backend:
    volumes:
      - ./Server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: nodemon --legacy-watch index.js

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"
