services:
  - type: web
    name: talent-track-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_REGISTRATION_KEY
        sync: false
      - key: ADMIN_REGISTRATION_KEY_NEW
        sync: false
      - key: CORS_ORIGIN
        value: https://pac-talent-track.web.app
      - key: NODE_ENV
        value: production
